config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  'posts#index'
  resources :posts, except: [:show] do
	  post "/like", to: "likes#like_toggle"
	  resources :comments, only: [:create, :destroy]
  end
  get '/posts/mypage' => 'posts#mypage'
  get  '/posts/show/:id'   => 'posts#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :likes
	has_many :liked_users, through: :likes, source: :user
	has_many :comments
    mount_uploader :image, PostImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments
  mount_uploader :avatar, AvatarUploader	
  def is_like?(post)
	  Like.find_by(user_id: self.id, post_id: post.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token, :only => [:create, :like_toggle]
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :null_session
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	def create
		new_comment = Comment.new(content: params[:content],post_id: params[:post_id],user_id: current_user.id)
		new_comment.save
		redirect_back(fallback_location: root_path)
	end 
	def destroy
		comment = Comment.find_by(id: params[:id])
		comment.destroy
		redirect_back(fallback_location: root_path)
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :authenticate_user!
	def like_toggle
		like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
		if like.nil?
			Like.create(user_id: current_user.id,
						post_id: params[:post_id])
		else
			like.destroy
		end
		
		redirect_to root_path
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show, :destroy]
  before_action :check_ownership, only: [:edit, :update, :destroy]
  def index
	  @posts = Post.paginate(page: params[:page], per_page: 10).order('created_at desc')
	  #@posts_count = current_user.posts.length 
  end

  def new
  end

  def create
	  new_post= Post.new(user_id: current_user.id, content: params[:content], image: params[:image], title: params[:title])
	  if new_post.save
		  redirect_to root_path
	  else
		  redirect_to new_post_path
	  end
  end
  
  def show
	  @post = Post.find_by(id: params[:id])
  end
  
  def mypage
	  @posts = current_user.posts
  end
  def edit
  end

  def update
	  @post.content = params[:content]
	  
	  if @post.save
		  redirect_to root_path
	  else
		  render :edit
	  end
  end
  
  def destroy
	  @post.destroy
	  redirect_to root_path
  end
	
  def check_ownership
	  @post = Post.find_by(id: params[:id])
	  redirect_to root_path if @post.user_id != current_user.id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<html>
  <head>
    <title>News Portal</title>
    <%= csrf_meta_tags %>
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>

  <body>
	  <nav class="blue darken-3">
		<div class="container nav-wrapper blue darken-3">
			<a href="/">
				<span id="header-large" style="font-weight:500;font-size:2.0rem;">News</span>
			</a>
			<ul id="nav-mobile" class="hide-on-med-and-down right">
				<% if user_signed_in? %>
					<li class="menu-item menu-item-type-post_type">
						<%= current_user.name %>님
					</li>
					<li class="menu-item menu-item-type-post_type">
						<%= link_to '로그아웃', destroy_user_session_path, method: 'delete'%>
					</li>
					<li class="menu-item menu-item-type-post_type">
					    <a href="/posts/new">글 작성</a>
					</li>
					<li class="menu-item menu-item-type-post_type">
						<a href="/posts/mypage">My page</a>
					</li>
				<% else %>
					<li class="menu-item menu-item-type-post_type">
					  	<a href="/users/sign_up">회원가입</a>
					</li>
					<li class="menu-item menu-item-type-post_type">
					  	<a href="/users/sign_in">로그인</a>
					</li>
				<% end %>
			</ul>	
		</div>
	  </nav>
	  <ul class="sidenav" id="mobile-demo">
			<li><a href="/posts">news</a></li>
			<li><a href="#">Sign in</a></li>
			<li><a href="#">Sign up</a></li>
			<li><a href="mobile.html">Mobile</a></li>
	  </ul>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="card horizontal">
  <div class="card-image">
		<a href="/posts/show/<%=post.id %>">
			<img src="<%= post.image.url %>">
		</a>
  </div> 
  <div class="card-stacked">
	  <a href="/posts/show/<%=post.id %>" style="color: black">
		  <div class="card-content">
			  <span class="card-title" style="font-weight:550;"><%= post.title.truncate(28, omission: '...')%></span>
			  <span><%= post.created_at %></span>
			  <p class="pre-line"><%= post.content.truncate(250, omission: '...') %></p>
		  </div>
	  </a>
	  <div class="card-action">
			  <%= post.likes.size %> 명이 좋아합니다
			  <% if user_signed_in? %>
				  <% if current_user.is_like?(post) %>
					<%= link_to "좋아요 취소", post_like_path(post), method: "post" %>
				  <% else %>
					<%= link_to "좋아요", post_like_path(post), method: "post" %>
				  <% end %>
				  <% if current_user.id == post.user_id %>
					<%= link_to "삭제", post_path(post), method: "delete", class: "right" %>
					<%= link_to "수정", edit_post_path(post), class: "right" %>
				  <% end %>
			  <% end %>
		</div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
	<div class="row">
		<div class="card col s12">
			<div class="card-content">
				<div class="card-title">
					수정하기	
				</div>
				<%= form_tag post_path(@post), method: "patch" do %>
				 <input type="hidden" name="id" value="<%=@post.id%>">
				 <div class="input-field">
					 <%= text_area_tag :content, @post.content, class: "materialize-textarea", placeholder: "무슨 생각을 하고 있나요?" %>
				</div>
				<div class="input-field">
					<%= button_tag "수정하기", class: "btn" %>
				</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
<div class="container">
	<hr width = "100%">
	<div class="section">
	<div class="section">
	<div class="row">
		<div class="col s12 m12">
			<% @posts.each do |post| %>
				  <%= render partial: "post", object: post %>
			<% end %>
		</div>
	</div>
	<div class="center">
		<%= will_paginate @posts %>
	</div>
</div>

app/views/posts/mypage.html.erb
<div class="container">
	<div class="row">
		<div class="col s12 m12">
			<% @posts.each do |post| %>
			  <%= render partial: "post", object: post %>
			<% end %>
		</div>
	</div>
</div>

app/views/posts/new.html.erb
<div class="container">
	<div class="row">
		<div class="card col s12">
			<div class="card-content">
				<div class="card-title">
					새 글 작성하기
				</div>
				<%= form_tag posts_path, multipart: true do %>
				<div class="input-field">
					 <%= file_field_tag :image %>
				</div> 
				<div class="input-field">
					 <%= text_area_tag :title, nil, class: "materialize-textarea", placeholder: "제목" %>
				</div>
				 <div class="input-field">
					 <%= text_area_tag :content, nil, class: "materialize-textarea", placeholder: "기사내용" %>
				</div>
				<div class="input-field">
					<%= button_tag "작성하기", class: "btn" %>
				</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<div class="container" style="width: 700px;">
	<hr width = "100%">
	<div class="section" align="center">
		<h4>
			<p style="font-weight:normal;"><%=@post.title%></p>
		</h4>
	</div>
	<div class="divider"></div>
	<div class="section" align="center">
		<img src="<%=@post.image.url %>" width=500 height=300>
	</div>
	<div class="divider"></div>
	<div class="section" style>
		<p class="pre-line"><%=@post.content%></p>
	</div>
	<div class="divider"></div>
	<% if user_signed_in? %>
	  <% if @post.comments.present? %>
		<ul class="collection">
		<% @post.comments.each do |comment| %>
			<li class="collection-item">
				<span class="title"><%= comment.user.name %></span>
				<p style="font-weight:200; font-size: 0.7em; color: gray"><%= comment.created_at %></p>
				<p class="pre-line">
					<%=comment.content %>
				</p>
				<% if comment.user.id == current_user.id %>
				  <div class><%= link_to "삭제", post_comment_path(@post, comment), method: "delete" %></div>
				<% end %>
			</li>
		<% end %>
		</ul>
	  <% end %>
	<% end %>
	<%= form_tag post_comments_path(@post) do %>
		<div class="input-field">
			<%= text_area_tag :content, nil, class:"materialize-textarea", placeholder: "댓글을 작성해주세요", required: true %>
		</div>
		<div class="input-field">
			<%= button_tag "댓글 쓰기", class: "btn" %>
		</div>
	<% end %>
</div>